# PLEASE DON'T PUT YOUR USER / PASS HERE (e.g.: "root"). Modify your own config/secrets.yml

# common settings for all databases
common: &common
  adapter: mysql2
  encoding: utf8mb4
  reconnect: true
  pool: 40
  local_infile: true
  username: <%= Rails.application.credentials.db[:username] %>
  password: <%= Rails.application.credentials.db[:password] %>
  database: <%= Rails.application.credentials.db[:name] %>

# common settings for any development databases
development:
  <<: *common
  host: localhost

test: &test
  <<: *common
  host: localhost

staging:
  <<: *common
  host: <%= Rails.application.credentials.db[:host] %>
  port: <%= Rails.application.credentials.db[:port] %>

production:
  <<: *common
  host: <%= Rails.application.credentials.db[:host] %>
  port: <%= Rails.application.credentials.db[:port] %>
